# Site
repository: thessaly/curriculum
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Julieta Arancio, PhD
#title: Your job title
email: jarancio@protonmail.com
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://julieta.aranc.io
# website_title: Web (Website title override)
download: CV in PDF for download
download_url: https://drive.google.com/file/d/1t2J_lM2QFpcEgdxb0hMCY9mY9_Xky25R/view?usp=sharing
#version_es: CV en español
#version_es_url: google.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: cassandreces
github_username:  thessaly
linkedin_username: aranciojulieta
orcid_username: 0000-0002-8624-4182

# Additional icon links
additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a <mark>researcher</mark> in Science and Technology Studies, an <mark>advocate</mark> for democratization of science and technology and a <mark>mentor</mark> for open hardware projects.   
  
  I enjoy learning and finding new ways of doing things, while contributing to  <mark>collaborative teams</mark> with a clear vision for change.
  
  You will usually find me in roles of translation between different kinds of expertise, in projects at the crossroads of <mark>technology, sustainability, science and education</mark>. 


content:
  - title: Skills
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Research
        link: 
        link_text: 
        additional_links:
        quote: 
        description: | # this will include new lines to allow paragraphs
            Research and curriculum design, conducting interviews and facilitating sessions with multiple stakeholders, collecting and analyzing big volumes of qualitative data, writing and editing scientific materials. 
      - layout: left
        title: Communications
        link: 
        link_text: 
        additional_links:
        quote: 
        description: | # this will include new lines to allow paragraphs
            Presentations and public speaking, writing for technical, informed and general audiences, basic [audio and video editing](https://youtu.be/Al0YMjiggxk), [radio production](https://www.mixcloud.com/mugreradial/), [educational game design](https://ohwmakers.github.io/treasure-hunt/) for a virtual session. 
      - layout: left
        title: Soft skills
        link: 
        link_text: 
        additional_links:
        quote: 
        description: | # this will include new lines to allow paragraphs
            Project management, problem-solving, conflict management, mentoring, fundraising, collaborative work, event organization.
      - layout: left
        title: Technical
        link: 
        link_text: 
        additional_links:
        quote: 
        description: | # this will include new lines to allow paragraphs
            Version control tools (git/GitHub/GitLab), basic web development (HTML, CSS, JS), Python and R scripts for data analysis, linked data [ontology design](http://www.visualdataweb.de/webvowl/#opts=filter_sco=true;#iri=https://raw.githubusercontent.com/cientopolis/appropedia-surgery/master/appropedia-skills.owl) using Protegé, operation of digital fabrication tools and programming of educational boards like Arduino, ESP32 or microBIT. 
      - layout: left
        title: Languages
        link: 
        link_text: 
        additional_links:
        quote: 
        description: | # this will include new lines to allow paragraphs
            I speak  Spanish (native), English (bilingual), French (A2) and some Portuguese. 
  - title: Ongoing projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Open Hardware Makers
        link: openhardware.space
        link_text: openhardware.space
        additional_links:
          #- title:  2019 - Present
           # icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: 
        description: | # this will include new lines to allow paragraphs
            Co-founder (2019) of a global mentorship program for open hardware projects. General strategy, project management, curriculum design and communications. I led a global consultation for improving our curriculum with the open hardware community. 
      - layout: left
        title: reGOSH 
        link: regosh.libres.cc
        link_text: regosh.libres.cc
        additional_links:
          #- title:  2019 - Present
           # icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote:
        description: | # this will include new lines to allow paragraphs
            Co-founder (2017) of the network, ex-coordinator of Buenos Aires node, in charge of the strategy working group. I co-organized a regional residency in 2019, having previously co-organized a Global Open Science Hardware (GOSH) event in Shenzhen, China, in 2018.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: CENIT-UNSAM
        sub_title: Associate researcher
        caption: 2015 - Present
        link: fund-cenit.org.ar
        quote: 
        description: | # this will include new lines to allow paragraphs
             Doctoral researcher (2016-2021). Collaborator in ‘Open, Collaborative and Alternative Science: overcoming health, inclusion and environmental challenges in Argentina’ (2015-2016) funded by the International Development Research Centre, Canada (OCSDnet).
      - layout: left
        title: Woodrow Wilson International Center for Scholars
        sub_title: Lead author
        caption: March 2021 - Present
        link: wilsoncenter.org
        quote: 
        description: | # this will include new lines to allow paragraphs
             Lead researcher and writer of a white paper seeking to understand the value of low cost and open source hardware for scientific research.
      - layout: left
        title: Global Open Science Hardware
        sub_title: Writer
        caption: Feb 2021 - Present
        link: openhardware.science
        quote: 
        description: | # this will include new lines to allow paragraphs
             Coordinating the drafting of workshop reports and a policy brief targeting universities' technology transfer offices
      - layout: left
        title: Journal of Open Hardware
        sub_title: Editor
        caption: 2020 - Present
        link: openhardware.metajnl.com
        quote: 
        description: | # this will include new lines to allow paragraphs
             Member of the Editorial Board of the Journal of Open Hardware (JOH), a peer reviewed open access publication for open hardware research and development.
      - layout: left
        title: Appropedia Foundation
        sub_title: Consultant
        caption: 2020 - Present
        link: appropedia.org
        quote: 
        description: | # this will include new lines to allow paragraphs
             Consultation services for a project in partnership with Intuitive Foundation (US), on the design and implementation of an ontology for remote learning of medical skills.
      - layout: left
        title: Wikimedia Switzerland
        sub_title: Wikidata instructor
        caption: 2019
        link: wikimedia.ch
        quote: 
        description: | # this will include new lines to allow paragraphs
            Designer and instructor of Wikidata workshops for undergrad students at École polytechnique fédérale de Lausanne (EPFL).
      - layout: left
        title: Personal Data IO
        sub_title: Community coordinator
        caption: November 2018 - May 2019
        link: personaldata.io
        quote: 
        description: | # this will include new lines to allow paragraphs
            Working directly with the founder of the startup, I was in charge of fundraising, communications and community coordination, plus co-development of a platform for users to easily ask for their personal data to companies online.
      - layout: left
        title: Geneva-Tsinghua Initiative, <br> University of Geneva
        sub_title: Mentor for Sustainable Development Goals' projects
        caption: July - September 2018
        link: gt-initiative.org
        quote: 
        description: | # this will include new lines to allow paragraphs
           Mentor of Master’s students’ projects addressing the SDGs with a focus on challenge-based learning, community building and management of open source projects.
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: PhD in Science and Technology Studies
        sub_title: Universidad Nacional de Quilmes <br> CONICET
        caption: 2016-2021
        quote: 
        description: | # this will include new lines to allow paragraphs
         My thesis (outstanding 10, with recommendation for publication) is titled *Technologies from dialogues: Open science hardware and democratization in the "peripheria"* and is available in Spanish at the UNQ online repository. 
      - layout: top-left
        title: Lic. in Environmental Science
        sub_title: Universidad de Buenos Aires
        caption: 2006-2011
        quote: 
        description: | # this will include new lines to allow paragraphs
          5-year degree at the Agronomy College, orientation technology. My thesis was titled *Quality assessment of sediments of the Reconquista River (Buenos Aires), with emphasis in heavy metals* and is available in Spanish at the [FAUBA online repository](http://ri.agro.uba.ar/files/intranet/intensificacion/2011aranciojulieta.pdf).
  - title: Funding received
    layout: list
    content:
      - layout: top-left
        title: Alfred P. Sloan Foundation
        sub_title: Postdoctoral research funding
        caption: 2021-2023
        quote: 
        description: | # this will include new lines to allow paragraphs
          Postdoctoral funding (USD 220,000) for two years at Drexel University, under supervision of Asoc. Prof. Gwen Ottinger
      - layout: top-left
        title: Mozilla Foundation
        sub_title: Science grant
        caption: 2020
        quote: 
        description: | # this will include new lines to allow paragraphs
          Personal grant (USD 12,000) supporting academic writing and community building
      - layout: top-left
        title: Shuttleworth Foundation
        sub_title: Flash grant
        caption: 2020
        quote: 
        description: | # this will include new lines to allow paragraphs
          Personal grant (USD 5,000) to advance project LogAir
      - layout: top-left
        title: National Science and Research Council of Argentina (CONICET)
        sub_title: PhD scholarship
        caption: 2016-2021
        quote: 
        description: | # this will include new lines to allow paragraphs
          Full support for pursuing my PhD at CENIT-UNSAM
  - title: Publications and presentations
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Academic writing
        #link: openhardware.space
        #link_text: openhardware.space
        #additional_links:
          #- title:  2019 - Present
           # icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #quote: 
        description: | # this will include new lines to allow paragraphs
            - Arancio, J. C. (2020, July 17). Opening Up The Tools For Doing Science: The Case Of The Global Open Science Hardware Movement. SocArXiv
            https://doi.org/10.31235 

            - Arancio, J. ‘Open science hardware: towards more democratic science and technology in Latin America?’ Proceedings of 15th International
            Symposium on Open Collaboration, University of Skövde, 2019. 

            - Arancio, J.; Molloy, J. ‘The Global Open Science Hardware Roadmap: A Collaborative Effort towards Democratising Science Hardware’, extended
            abstract for Tech4Dev Conference 2018 - UNESCO/EPFL (Lausanne, SZ) 
        
            - Arancio, J.; Sebastian, S.; Schwertz-Weirich, A.; Actis, G.; Cremaschi, A.; Arancibia, F.; Van Zwanenberg, P.; Fressoli, M. ‘Relato de experiencia -
            Workshop internacional de desarrollo abierto y colaborativo’ in Liinc Em Revista, 2018 https://doi.org/10.18617/liinc.v14i1.4132 
      - layout: left
        title: Non-academic writing
        #link: openhardware.space
        #link_text: openhardware.space
        #additional_links:
          #- title:  2019 - Present
           # icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #quote: 
        description: | # this will include new lines to allow paragraphs
            - Arancio, J. ‘Open Science Hardware contributes to aligning the research agenda with societal needs’, in Journal of Open Hardware Blog, 2020 

            - Dosemagen, S; Arancio, J. ‘Open Hardware Distribution & Documentation Working Group series’, in Journal of Open Hardware Blog, 2020 

            - Arancio, J. ‘Open science hardware across the Andes’ in GOSH blog, 2018 

            - Arancio, J. ‘GOSH Roadmap: democratising technology, from a Latin American perspective’, in STEPS Centre Blog, 2018 

            - Arancio, J. ‘OpenCon 2017: Des-idealizando lo abierto para una mejor apertura’ in PlanC blog, 2018 

            - Arancio, J.; Fressoli, M.; Arza, V. ‘Agroecology meets open source technologies’ in OCSDnet Blog, 2016
      - layout: left
        title: Conferences & Workshops
        #link: openhardware.space
        #link_text: openhardware.space
        #additional_links:
          #- title:  2019 - Present
           # icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #quote: 
        description: | # this will include new lines to allow paragraphs
            - STS Switzerland 2021 Conference (15-17 February 2021, Virtual) - Presenting author 

            - 4S/EASST Conference (18-20 August 2020, Virtual) - Presenting author 

            - Doctoral Consortium - OpenSym (2019, Sweden) - Presenting author 

            - Global Open Science Hardware gathering (2018, China) - Organizing committee 

            - Mozilla Festival (2018, London) - Presenting author

            - OpenCon Swiss (2018, Bern) - Speaker 

            - Tech4Dev (2018, Lausanne) - Presenting author 

            - TECNOx (2018, Chile) - Speaker 
  - title: When I'm not working
    layout: text
    content: | # this will include new lines to allow paragraphs
          You can usually find me reading comics, drawing my first comic (in progress!), playing the [flute or clarinet](https://www.youtube.com/watch?v=xsb5qIvQ7J4&list=PLMuoRZ8V_6mknMTVpHpaYm9oC-rN33VJR), writing some [poetry in Spanish](https://thessaly.github.io/palabras/) or riding my bicycle. 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
